yq_git: Set apply=no for SRC_URI diff
Issue: LIN1024-2114

Fixed a do_patch error use git shallow tarball (BB_GIT_SHALLOW = "1"):

$ bitbake yp -cpatch

ERROR: do_patch: Importing patch 'github.com.pkg.diff' with striplevel '1'

The github.com.pkg.diff is ud.clonedir of git://github.com/pkg/diff:
* When use regular git repo as source, oe.patch.patch_path() will NOT
  handle it as a patch since the directory github.com.pkg.diff exists,
  and nothing is wrong.

* When use git shallow tarball, the github.com.pkg.diff doesn't exist since
  it is fetched as a tarball, then oe.patch.patch_path() will handle it
  as a patch, then the error happens.

(LOCAL REV: NOT UPSTREAM) - Send to upstream on 20240619

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>